[project]
name = "parts-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asgiref",
    "click",
    "colorama",
    "cssbeautifier",
    "django",
    "djlint",
    "editorconfig",
    "html-tag-names",
    "html-void-elements",
    "jsbeautifier",
    "json5",
    "pathspec",
    "pip",
    "psycopg",
    "psycopg-binary",
    "python-dotenv",
    "pyyaml",
    "regex",
    "six",
    "sqlparse",
    "tqdm",
    "typing-extensions",
]
