# Generated by Django 5.1.2 on 2024-10-18 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_item_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantitem',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 16, 18, 39, 572272, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='minlevel',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 18, 16, 18, 39, 573276, tzinfo=datetime.timezone.utc)),
        ),
    ]
